/* ============================================================
   TARTER YARD MAP — catálogo de nombres de producto
   ------------------------------------------------------------
   SKU → nombre del producto, para que al escanear un código de
   barras la app muestre el producto escrito y no un número.

     n = nombre del producto
     b = marca

   Esta es la base que viene con la app (sacada de fotos3point.xlsx).
   El reporte de inventario que carga el administrador aporta el
   resto de los nombres y manda sobre esta lista.

   Generado por tools/build-barcode-map.py — no editar a mano.
   104 productos con nombre
   ============================================================ */
window.__SEED_CATALOG__ = {
  "1BPCL": {"n": "One Bottom Plow — Yellow", "b": "CountyLine"},
  "2BPCL": {"n": "Two Bottom Plow — Yellow", "b": "CountyLine"},
  "2RWUCL": {"n": "2\" Receiver Wire Unroller — Yellow", "b": "CountyLine"},
  "ATVCPDC": {"n": "ATV Disc Culti-Packer Combo", "b": "Tarter"},
  "ATVDB4": {"n": "Drawbar for Chain Harrow, 4' Universal", "b": "Tarter"},
  "ATVFD": {"n": "ATV Flip Disc — Gray", "b": "Tarter"},
  "ATVH48": {"n": "ATV/UTV Chain Harrow, 4' x 8'", "b": "Tarter"},
  "ATVTD8": {"n": "ATV 8-Blade Disc Harrow", "b": "Tarter"},
  "ATVWU": {"n": "ATV Wire Unroller Hitch-Mount — Yellow", "b": "Tarter"},
  "BB104BL": {"n": "100 Series Box Blade, 4 ft — Black", "b": "Tarter"},
  "BB205BL": {"n": "Box Blade (cuchilla de caja) — 200 Series, 5 ft", "b": "Tarter"},
  "BB206BL": {"n": "Box Blade (cuchilla de caja) — 200 Series, 6 ft", "b": "Tarter"},
  "BB306BL": {"n": "6' Box Blade, 300 Series — Black", "b": "Tarter"},
  "BB307BL": {"n": "7' Box Blade, 300 Series — Black", "b": "Tarter"},
  "BB5CL": {"n": "CountyLine 5 ft Box Blade", "b": "CountyLine"},
  "BB6CL": {"n": "Box Blade (cuchilla de caja) — 6 ft", "b": "CountyLine"},
  "BBSC4CL": {"n": "Box Blade (cuchilla de caja) — Sub-Compact, 4 ft", "b": "CountyLine"},
  "BP20BL": {"n": "Bale Prong / Bale Spear (lanza para pacas) — 20 ft", "b": "Tarter"},
  "BP30BL": {"n": "Bale Prong / Bale Spear (lanza para pacas) — 30 ft", "b": "Tarter"},
  "BPCL": {"n": "Bale Prong / Bale Spear (lanza para pacas)", "b": "CountyLine"},
  "BR52": {"n": "52\" Bucket Rake"},
  "BR68": {"n": "68\" Bucket Rake"},
  "BSBL": {"n": "Bale Spear (lanza para pacas)", "b": "Tarter"},
  "BSCL": {"n": "Bale Spear (lanza para pacas)", "b": "CountyLine"},
  "BSQA-2BL": {"n": "Bale Spear Quick Attach, Double — Black", "b": "Tarter"},
  "BXSQ": {"n": "Bextra Large Square Bale Feeder"},
  "CA20BL": {"n": "Carry All (canastilla de carga) — 20 ft", "b": "Tarter"},
  "CACL": {"n": "Carry All (canastilla de carga)", "b": "CountyLine"},
  "CULCL": {"n": "Cultivator (cultivadora)", "b": "CountyLine"},
  "DH105BL": {"n": "Disc Harrow (rastra de discos) — 100 Series, 5 ft", "b": "Tarter"},
  "DH206BL": {"n": "Disc Harrow (rastra de discos) — 200 Series, 6 ft", "b": "Tarter"},
  "DH307BL": {"n": "Disc Harrow (rastra de discos) — 300 Series, 7 ft", "b": "Tarter"},
  "DH317BL": {"n": "7' Disc Harrow, 300 Series — Black", "b": "Tarter"},
  "FC201BL": {"n": "200 Series One-Row Cultivator — Black", "b": "Tarter"},
  "FM165WC": {"n": "Feed Master 165 w/ Cage", "b": "Tarter"},
  "FM205": {"n": "5 ft Finish Mower, 200 Series", "b": "Tarter"},
  "FM206": {"n": "Finish Mower (podadora de acabado) — 200 Series, 6 ft", "b": "Tarter"},
  "FM5CL": {"n": "5' Finish Mower — Yellow", "b": "CountyLine"},
  "FM6CL": {"n": "6' Finish Mower — Yellow", "b": "CountyLine"},
  "GB104BL": {"n": "Rear Grader Blade (cuchilla niveladora) — 100 Series, 4 ft", "b": "Tarter"},
  "GB205BL": {"n": "Rear Grader Blade (cuchilla niveladora) — 200 Series, 5 ft", "b": "Tarter"},
  "GB206BL": {"n": "200 Series Rear Grader Blade, 6 ft — Black", "b": "Tarter"},
  "GB207BL": {"n": "Rear Grader Blade (cuchilla niveladora) — 200 Series, 7 ft", "b": "Tarter"},
  "GB306BL": {"n": "6' Grader Blade, 300 Series — Black", "b": "Tarter"},
  "GB307BL": {"n": "7' Grader Blade, 300 Series — Black", "b": "Tarter"},
  "GB5CL": {"n": "Rear Grader Blade (cuchilla niveladora) — 5 ft", "b": "CountyLine"},
  "GB6CL": {"n": "Rear Grader Blade (cuchilla niveladora) — 6 ft", "b": "CountyLine"},
  "GB7CL": {"n": "Rear Grader Blade (cuchilla niveladora) — 7 ft", "b": "CountyLine"},
  "GMF": {"n": "Goat Mineral Feeder"},
  "HF20BL": {"n": "200 Series 3-Point Hay Fork — Black", "b": "Tarter"},
  "HF30BL": {"n": "300 Series 3-Point Hay Fork — Black", "b": "Tarter"},
  "LG114.5BL": {"n": "4.5' Land Grader, 100 Series — Black", "b": "Tarter"},
  "LG215BL": {"n": "5' Land Grader, 200 Series — Black", "b": "Tarter"},
  "LG216BL": {"n": "6' Land Grader, 200 Series — Black", "b": "Tarter"},
  "LG318BL": {"n": "8' Land Grader, 300 Series — Black", "b": "Tarter"},
  "LR104BL": {"n": "Landscape Rake (rastrillo) — 100 Series, 4 ft", "b": "Tarter"},
  "LR205BL": {"n": "Landscape Rake (rastrillo) — 200 Series, 5 ft", "b": "Tarter"},
  "LR206BL": {"n": "200 Series Landscape Rake, 6 ft — Black", "b": "Tarter"},
  "LR207BL": {"n": "Landscape Rake (rastrillo) — 200 Series, 7 ft", "b": "Tarter"},
  "LR306BL": {"n": "6' Landscape Rake, 300 Series — Black", "b": "Tarter"},
  "LR307BL": {"n": "7' Landscape Rake, 300 Series — Black", "b": "Tarter"},
  "LR5CL": {"n": "Landscape Rake (rastrillo) — 5 ft", "b": "CountyLine"},
  "LR6CL": {"n": "Landscape Rake (rastrillo) — 6 ft", "b": "CountyLine"},
  "LR7CL": {"n": "Landscape Rake (rastrillo) — 7 ft", "b": "CountyLine"},
  "LRSC4CL": {"n": "Landscape Rake (rastrillo) — Sub-Compact, 4 ft", "b": "CountyLine"},
  "LRWK": {"n": "Landscape Rake Wheel Kit (juego de ruedas)", "b": "Tarter"},
  "MB20BL": {"n": "Middle Buster (arado surcador) — 20 ft", "b": "Tarter"},
  "MBCL": {"n": "Middle Buster (arado surcador)", "b": "CountyLine"},
  "MBSS10BL": {"n": "Middle Buster / Sub-Soiler Combo, 100 Series — Black", "b": "Tarter"},
  "MBSSSCCL": {"n": "Middle Buster / Subsoiler, Sub-Compact", "b": "CountyLine"},
  "MP201BL": {"n": "1-Bottom Moldboard Plow, 200 Series — Black", "b": "Tarter"},
  "MP202BL": {"n": "2-Bottom Moldboard Plow, 200 Series — Black", "b": "Tarter"},
  "MS1002": {"n": "Compact Manure Spreader — 13 cu ft", "b": "Tarter"},
  "MS1002CL": {"n": "CountyLine Manure Spreader — 10 bushel", "b": "CountyLine"},
  "PFQA12WBL": {"n": "Pallet Fork Quick Attach Walk-Thru, 1200 lb — Black", "b": "Tarter"},
  "PFQAWBL": {"n": "Pallet Fork Quick Attach Walk-Thru, 3000 lb — Black", "b": "Tarter"},
  "QASP6": {"n": "Quick Attach Snow Pusher, 6'", "b": "Tarter"},
  "QASP7": {"n": "Quick Attach Snow Pusher, 7' — Yellow", "b": "Tarter"},
  "QASP8": {"n": "Quick Attach Snow Pusher, 8'", "b": "Tarter"},
  "QH201BL": {"n": "3-Point Category 1 Quick Hitch — Black", "b": "Tarter"},
  "RBRC502CL": {"n": "Round Back Rotary Cutter, 5' Series 2", "b": "CountyLine"},
  "RC104BL": {"n": "100 Series Rotary Cutter, 4 ft — Black", "b": "Tarter"},
  "RC205BL": {"n": "200 Series Rotary Cutter, 5 ft — Black", "b": "Tarter"},
  "RC206BL": {"n": "200 Series Rotary Cutter, 6 ft — Black", "b": "Tarter"},
  "RC306BL": {"n": "6' Rotary Cutter, 300 Series — Black", "b": "Tarter"},
  "RT104BL": {"n": "Rotary Tiller (rotocultivador) — 100 Series, 4 ft", "b": "Tarter"},
  "RT205BL": {"n": "Rotary Tiller (rotocultivador) — 200 Series, 5 ft", "b": "Tarter"},
  "RT206BL": {"n": "Rotary Tiller (rotocultivador) — 200 Series, 6 ft", "b": "Tarter"},
  "RT207BL": {"n": "Rotary Tiller (rotocultivador) — 200 Series, 7 ft", "b": "Tarter"},
  "RT4LDCL": {"n": "Rotary Tiller (rotocultivador)", "b": "CountyLine"},
  "RT5CL": {"n": "Rotary Tiller, 5' — Yellow", "b": "CountyLine"},
  "RT6CL": {"n": "Rotary Tiller, 6' — Yellow", "b": "CountyLine"},
  "RT7CL": {"n": "Rotary Tiller, 7' — Yellow", "b": "CountyLine"},
  "RTFK4CL": {"n": "Rotary Tiller (rotocultivador)", "b": "CountyLine"},
  "RTFK5CL": {"n": "Rotary Tiller (rotocultivador)", "b": "CountyLine"},
  "RTFK6CL": {"n": "Rotary Tiller (rotocultivador)", "b": "CountyLine"},
  "SP6BDK": {"n": "6' Snow Pusher Backdrag Kit", "b": "Tarter"},
  "SP7BDK": {"n": "7' Snow Pusher Backdrag Kit — Yellow", "b": "Tarter"},
  "SP8BDK": {"n": "8' Snow Pusher Backdrag Kit", "b": "Tarter"},
  "SS20BL": {"n": "200 Series Subsoiler — Black", "b": "Tarter"},
  "SUBCL": {"n": "Subsoiler (subsolador)", "b": "CountyLine"},
  "TGQA54-2BL": {"n": "Tine Grapple Quick Attach 54\", 2-Clamp — Black", "b": "Tarter"},
  "TM20BL": {"n": "200 Series Trailer Mover — Black", "b": "Tarter"},
  "WS20BL": {"n": "200 Series 3-Point Wire Stretcher — Black", "b": "Tarter"}
};
